### ISSUE TITLE
ButtonPushed error

### ISSUE THREAD

**Issue by jycamus90** [spideruci/cerebro-layout#3]
When I click a node, I keep getting a message 'Selection begins at ......'. If I keep clicking nodes, I get the error message that I copied below. I will look into it but I wanted to create a report.

```
>> Selection begins at 70.000000 429.000000
Selection begins at 329.000000 392.000000
Selection begins at 429.000000 298.000000
Selection begins at 429.000000 298.000000
Selection begins at 429.000000 298.000000
Selection begins at 429.000000 298.000000
59:event/CircularShifter:update(Ljava/util/Observable;Ljava/lang/Object;)V:104
java.lang.Exception
OKAY! Something went wrong.
Feel free to report this exception.
Continue using the command menu... 
    at org.spideruci.cerebro.layout.ViewerEventListener.buttonPushed(ViewerEventListener.java:215)
    at org.graphstream.ui.swingViewer.ViewerPipe.nodeAttributeAdded(ViewerPipe.java:157)
    at org.graphstream.stream.SourceBase.sendAttributeChangedEvent(SourceBase.java:815)
    at org.graphstream.stream.SourceBase.sendNodeAttributeAdded(SourceBase.java:699)
    at org.graphstream.stream.thread.ThreadProxyPipe.processMessage(ThreadProxyPipe.java:577)
    at org.graphstream.stream.thread.ThreadProxyPipe.pump(ThreadProxyPipe.java:264)
    at org.graphstream.ui.swingViewer.ViewerPipe.pump(ViewerPipe.java:94)
    at org.spideruci.cerebro.layout.ViewerEventListener.mouseClicked(ViewerEventListener.java:57)
    at java.awt.Component.processMouseEvent(Component.java:6538)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by VijayKrishna** [comment]
Remove this line: https://github.com/spideruci/cerebro-layout/blob/master/src/main/java/org/spideruci/cerebro/layout/ViewerEventListener.java#L215
